services:
  nginx:
    image: $NGINX_VERSION
    container_name: $NGINX_NAME
    restart: always
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - /app/Trabajo/wordpress-sites/services/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx
    networks:
      - nginx-network
volumes:
  nginx-logs:
    driver: local

networks:
  nginx-network:
    driver: bridge

