services:
  wordpress:
    image: $WORDPRESS_VERSION
    restart: always
    container_name: $WORDPRESS_CONTAINER_NAME
    ports:
      - "$WORDPRESS_HOST_PORT"
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    command:
      sh -c "apt update && apt install -y vim && docker-entrypoint.sh apache2-foreground"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
  db:
    image: $MYSQL_VERSION
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: $WORDPRESS_CONTAINER_NAME_DB
    environment:
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
